/**
 * Setup Report Module
 * Generates detailed setup reports
 */

import fs from 'fs-extra';
import path from 'path';
import { getPaths } from '../utils/paths.js';
import { logger } from '../utils/log.js';
import type { LazyConfig, SystemInfo, NetworkInfo } from '../types/index.js';

interface ReportData {
  config: LazyConfig;
  systemInfo: SystemInfo;
  networkInfo: NetworkInfo;
}

export async function createReport(data: ReportData): Promise<void> {
  const paths = getPaths();
  const reportPath = path.join(paths.root, 'setup-report.txt');

  const report = generateReportContent(data);

  await fs.writeFile(reportPath, report, 'utf-8');
  logger.info(`Setup report saved to ${reportPath}`);
}

function generateReportContent(data: ReportData): string {
  const { config, systemInfo, networkInfo } = data;
  const timestamp = new Date().toISOString();

  const lines = [
    '════════════════════════════════════════════════════════',
    '                 LAZYCRAFT LAUNCHER REPORT              ',
    '════════════════════════════════════════════════════════',
    '',
    `Generated: ${timestamp}`,
    '',
    '── SYSTEM INFORMATION ──────────────────────────────────',
    `Operating System: ${systemInfo.os}`,
    `Total RAM: ${systemInfo.totalRAMGB} GB`,
    `Available RAM: ${systemInfo.availableRAMGB} GB`,
    `Java Installed: ${systemInfo.javaInstalled ? 'Yes' : 'No'}`,
    `Java Version: ${systemInfo.javaVersion || 'Not detected'}`,
    `Java Path: ${systemInfo.javaPath || config.javaPath || 'Not found'}`,
    '',
    '── SERVER CONFIGURATION ────────────────────────────────',
    `Server Type: ${config.serverType}`,
    `Minecraft Version: ${config.minecraftVersion}`,
    `Allocated RAM: ${config.ramGB} GB`,
    `Server Port: ${config.port}`,
    `Game Profile: ${config.profile}`,
    `World Path: ${config.worldPath}`,
    `New World: ${config.isNewWorld ? 'Yes' : 'No'}`,
    `EULA Accepted: ${config.eulaAccepted ? 'Yes' : 'No'}`,
    `UPnP Enabled: ${config.upnpEnabled ? 'Yes' : 'No'}`,
    `Backup on Exit: ${config.backupOnExit ? 'Yes' : 'No'}`,
    '',
    '── NETWORK CONFIGURATION ───────────────────────────────',
    `LAN IP Address: ${networkInfo.lanIP}:${networkInfo.port}`,
    `Public IP Address: ${networkInfo.publicIP ? `${networkInfo.publicIP}:${networkInfo.port}` : 'Not available'}`,
    `UPnP Status: ${networkInfo.upnpSuccess ? 'Successfully mapped' : 'Failed or disabled'}`,
    `Port Reachability: ${networkInfo.reachable ? 'Publicly accessible ✓' : 'LAN only ⚠'}`,
    '',
    '── CONNECTION INSTRUCTIONS ─────────────────────────────',
    '',
    'For players on your local network:',
    `  Connect to: ${networkInfo.lanIP}:${networkInfo.port}`,
    '',
  ];

  if (networkInfo.publicIP && networkInfo.reachable) {
    lines.push(
      'For players outside your network:',
      `  Connect to: ${networkInfo.publicIP}:${networkInfo.port}`,
      ''
    );
  } else if (networkInfo.publicIP && !networkInfo.reachable) {
    lines.push(
      'For external access (currently blocked):',
      '  1. Enable UPnP on your router, OR',
      `  2. Manually forward TCP port ${networkInfo.port} to ${networkInfo.lanIP}, OR`,
      '  3. Use Tailscale or similar VPN service',
      ''
    );
  }

  lines.push(
    '── TROUBLESHOOTING ─────────────────────────────────────',
    '',
    'If players cannot connect:',
    '  • Ensure Windows Firewall allows Java',
    '  • Check router port forwarding settings',
    '  • Verify server is running (check Dashboard)',
    '  • Try connecting via LAN IP first',
    '',
    '── EULA NOTICE ─────────────────────────────────────────',
    '',
    `EULA accepted at: ${timestamp}`,
    'By using this server, you agree to the Minecraft EULA:',
    'https://www.minecraft.net/eula',
    '',
    '════════════════════════════════════════════════════════',
    '           Report generated by LazyCraftLauncher         ',
    '            "You ask to play, we host for you"           ',
    '════════════════════════════════════════════════════════',
  );

  return lines.join('\n');
}

export async function loadReport(): Promise<string | null> {
  try {
    const paths = getPaths();
    const reportPath = path.join(paths.root, 'setup-report.txt');

    if (await fs.pathExists(reportPath)) {
      return await fs.readFile(reportPath, 'utf-8');
    }
  } catch (error) {
    logger.error('Error loading report:', error);
  }

  return null;
}
